import * as fs from "fs";
import * as path from "path";
import type { VpsScaffoldResult } from "../types/vps";

// The scaffold is a deterministic deploy pipeline for the supported case:
// a static build served by Caddy on a fresh Ubuntu/Debian server. The local
// orchestrator is Node (portable, no local shell assumptions); the remote
// scripts are bash and run on the server. Everything is committed to the app
// repo so `npm run deploy` works with or without Dyad.

const DEPLOY_MJS = `// Deploys this app to your server, as configured in dyad.deploy.json.
// Run with: npm run deploy
// Generated by Dyad; edit freely, this file is yours.
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";

const config = JSON.parse(readFileSync("dyad.deploy.json", "utf8"));
const port = config.port ?? 22;
const keyPath = join(homedir(), ".ssh", config.keyName ?? "dyad_deploy_ed25519");
const destination = \`\${config.user}@\${config.host}\`;
const distDir = config.distDir ?? "dist";

const SSH_OPTS = [
  "-o", "BatchMode=yes",
  "-o", "StrictHostKeyChecking=accept-new",
  "-i", keyPath,
];

function stage(name) {
  console.log(\`::dyad-deploy-stage::\${name}\`);
}

function run(command, args, opts = {}) {
  const result = spawnSync(command, args, { stdio: "inherit", ...opts });
  if (result.error) {
    console.error(\`Failed to run \${command}: \${result.error.message}\`);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error(\`\${command} exited with code \${result.status}\`);
    process.exit(result.status ?? 1);
  }
}

function ssh(remoteCommand) {
  run("ssh", [...SSH_OPTS, "-p", String(port), destination, remoteCommand]);
}

function scp(localPath, remotePath) {
  run("scp", [...SSH_OPTS, "-P", String(port), localPath, \`\${destination}:\${remotePath}\`]);
}

stage("build");
// Force a production build regardless of the caller's NODE_ENV. A non-
// production value makes some frameworks (e.g. Next.js) emit broken output.
run("npm", ["run", "build"], {
  shell: process.platform === "win32",
  env: { ...process.env, NODE_ENV: "production" },
});

stage("upload");
const workDir = mkdtempSync(join(tmpdir(), "dyad-deploy-"));
const tarball = join(workDir, "release.tar.gz");
// tar ships with macOS, Linux, and Windows 10+.
run("tar", ["-czf", tarball, "-C", distDir, "."]);
ssh("mkdir -p /tmp/dyad-deploy");
scp(tarball, "/tmp/dyad-deploy/release.tar.gz");
scp("deploy/remote/setup.sh", "/tmp/dyad-deploy/setup.sh");
scp("deploy/remote/deploy.sh", "/tmp/dyad-deploy/deploy.sh");
rmSync(workDir, { recursive: true, force: true });

stage("remote-setup");
const domainArg = config.domain ?? "";
ssh(\`bash /tmp/dyad-deploy/setup.sh '\${config.remotePath}' '\${domainArg}'\`);

stage("remote-deploy");
ssh(\`bash /tmp/dyad-deploy/deploy.sh '\${config.remotePath}'\`);

stage("finalize");
const url = config.domain ? \`https://\${config.domain}\` : \`http://\${config.host}\`;
console.log(\`Deployed: \${url}\`);
`;

const SETUP_SH = `#!/usr/bin/env bash
# One-time server setup for a static site served by Caddy. Idempotent: safe to
# re-run; skips work it has already done. Assumes a fresh Ubuntu/Debian server.
# Usage: setup.sh <remote_path> [domain]
set -euo pipefail

REMOTE_PATH="$1"
DOMAIN="\${2:-}"
MARKER="$REMOTE_PATH/.dyad-setup-complete"

SUDO=""
if [ "$(id -u)" -ne 0 ]; then
  SUDO="sudo"
fi

if [ -f "$MARKER" ]; then
  echo "Setup already complete, skipping."
  exit 0
fi

if ! command -v caddy >/dev/null 2>&1; then
  echo "Installing Caddy..."
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key | $SUDO gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt | $SUDO tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq caddy
fi

$SUDO mkdir -p "$REMOTE_PATH/releases"

SITE_ADDRESS="\${DOMAIN:-:80}"
echo "Configuring Caddy for $SITE_ADDRESS"
$SUDO tee /etc/caddy/Caddyfile >/dev/null <<CADDYFILE
$SITE_ADDRESS {
	root * $REMOTE_PATH/current
	encode gzip
	try_files {path} /index.html
	file_server
}
CADDYFILE
$SUDO systemctl reload caddy

$SUDO touch "$MARKER"
echo "Setup complete."
`;

const REMOTE_DEPLOY_SH = `#!/usr/bin/env bash
# Publishes an uploaded release: unpack, flip the current symlink, prune old
# releases. Usage: deploy.sh <remote_path>
set -euo pipefail

REMOTE_PATH="$1"
TARBALL="/tmp/dyad-deploy/release.tar.gz"
RELEASE="$REMOTE_PATH/releases/$(date +%Y%m%d%H%M%S)"

SUDO=""
if [ "$(id -u)" -ne 0 ]; then
  SUDO="sudo"
fi

$SUDO mkdir -p "$RELEASE"
$SUDO tar -xzf "$TARBALL" -C "$RELEASE"
$SUDO ln -sfn "$RELEASE" "$REMOTE_PATH/current"
rm -f "$TARBALL"

cd "$REMOTE_PATH/releases"
ls -1t | tail -n +6 | while read -r old; do
  $SUDO rm -rf "$REMOTE_PATH/releases/$old"
done

echo "Release published: $RELEASE"
`;

interface ScaffoldFile {
  relativePath: string;
  contents: string;
}

const SCAFFOLD_FILES: ScaffoldFile[] = [
  { relativePath: path.join("deploy", "deploy.mjs"), contents: DEPLOY_MJS },
  {
    relativePath: path.join("deploy", "remote", "setup.sh"),
    contents: SETUP_SH,
  },
  {
    relativePath: path.join("deploy", "remote", "deploy.sh"),
    contents: REMOTE_DEPLOY_SH,
  },
];

export function isScaffoldPresent(appPath: string): boolean {
  return fs.existsSync(path.join(appPath, "deploy", "deploy.mjs"));
}

/**
 * Writes the deploy pipeline files and registers the `deploy` npm script.
 * Existing files are never overwritten: once scaffolded, the files belong to
 * the user (or a future agent flow) and may have been customized.
 */
export function scaffoldDeployFiles(appPath: string): VpsScaffoldResult {
  const written: string[] = [];
  const skipped: string[] = [];

  for (const file of SCAFFOLD_FILES) {
    const target = path.join(appPath, file.relativePath);
    if (fs.existsSync(target)) {
      skipped.push(file.relativePath);
      continue;
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, file.contents, "utf8");
    written.push(file.relativePath);
  }

  const packageJsonPath = path.join(appPath, "package.json");
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
  packageJson.scripts ??= {};
  if (packageJson.scripts.deploy === undefined) {
    packageJson.scripts.deploy = "node deploy/deploy.mjs";
    fs.writeFileSync(
      packageJsonPath,
      `${JSON.stringify(packageJson, null, 2)}\n`,
      "utf8",
    );
    written.push("package.json (deploy script)");
  } else {
    skipped.push("package.json (deploy script)");
  }

  return { written, skipped };
}
